spring.application.name=FoodApp

server.port=8080

# MYSQL CONNECTION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update



secreteJwtString=${JWT_SECRET}

## Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

## AWS CONFIG
aws.s3.region=eu-north-1
aws.s3.bucket=nancy-food-app
aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
logging.level.javax.mail=DEBUG



## LOCAL REACT FRONTEND
base.payment.link=https://food-ordering-app-1-skrn.onrender.com/pay?orderid=
frontend.base.url=https://food-ordering-app-1-skrn.onrender.com



## RAZORPAY CREDENTIALS
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
